### ISSUE TITLE
老哥你好，我OCI报错，能帮忙排解一下吗？

### ISSUE THREAD

**Issue by Gestepo** [TwoPlusEight/pagermaid-pyro-oci#1]
很抱歉，提了第一个issue

INFO [2023-12-30 07:15:18] [pagermaid] 加载插件: da, dme, epic, fadian, keyword, lottery, oracle_obdt, speed_test
INFO [2023-12-30 07:15:18] [pagermaid] 模块 oracle_obdt 加载出错: No module named 'oci'

实际上，pip install oci了，pip list 也有。

**Comment by TwoPlusEight** [comment]
**_不太上GitHub回复晚了十分抱歉_**

是否有使用虚拟环境
可以查看目录中有无venv(一般是)，如果存在需要使用虚拟环境中的pip安装oci

或在import后插入
```python
from pagermaid.utils import pip_install
pip_install("oci")
```
然后在聊天中使用,reload重载

**Comment by Gestepo** [comment]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

> **_不太上GitHub回复晚了十分抱歉_**
> 
> 是否有使用虚拟环境 可以查看目录中有无venv(一般是)，如果存在需要使用虚拟环境中的pip安装oci
> 
> 或在import后插入
> 
> ```python
> from pagermaid.utils import pip_install
> pip_install("oci")
> ```
> 
> 然后在聊天中使用,reload重载

感谢回复，但是老哥，我还是报错。（是真不知道啥原因了
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
![oci报错](https://github.com/TwoPlusEight/pagermaid-pyro-oci/assets/28818297/1149d5a7-df46-4a67-9e40-ebe567407a4a)

**Comment by TwoPlusEight** [comment]
您再下载新的尝试一次，由于自身也没碰到过此类问题也较为困惑，只能提供一些可能的解决方案😶‍🌫️
十分抱歉

**Comment by Gestepo** [comment]
老哥您太客气了，应该是我自身的原因，感谢分享。我自己在摸排一下！
